In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\HP\Downloads\Data Science\Final_Projects\retail-intelligence-analytics\data\raw.csv")

In [4]:
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

In [23]:
df.shape

(779425, 8)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  object
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 65.1+ MB

In [8]:
df.describe()

           Quantity         Price    Customer ID
count  1.067371e+06  1.067371e+06  824364.000000
mean   9.938898e+00  4.649388e+00   15324.638504
std    1.727058e+02  1.235531e+02    1697.464450
min   -8.099500e+04 -5.359436e+04   12346.000000
25%    1.000000e+00  1.250000e+00   13975.000000
50%    3.000000e+00  2.100000e+00   15255.000000
75%    1.000000e+01  4.150000e+00   16797.000000
max    8.099500e+04  3.897000e+04   18287.000000

In [11]:
df.isnull().sum()

Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
dtype: int64

In [13]:
# handling missing values

df = df.dropna(subset=['Customer ID'])

In [18]:
# Fixing data type

df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 824364 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      824364 non-null  object
 1   StockCode    824364 non-null  object
 2   Description  824364 non-null  object
 3   Quantity     824364 non-null  int64
 4   InvoiceDate  824364 non-null  datetime64[ns]
 5   Price        824364 non-null  float64
 6   Customer ID  824364 non-null  object
 7   Country      824364 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 56.6+ MB

In [16]:
df['Customer ID'] = df['Customer ID'].astype(str)

In [20]:
# removing negative values

df = df[df['Quantity']>0]
df = df[df['Price']>0]

In [21]:
df.describe()

            Quantity                    InvoiceDate          Price
count  805549.000000                         805549  805549.000000
mean       13.290522  2011-01-02 10:24:44.106814464       3.206561
min         1.000000            2009-12-01 07:45:00       0.001000
25%         2.000000            2010-07-07 12:08:00       1.250000
50%         5.000000            2010-12-03 15:10:00       1.950000
75%        12.000000            2011-07-28 13:05:00       3.750000
max     80995.000000            2011-12-09 12:50:00   10953.500000
std       143.634088                            NaN      29.199173

In [22]:
df = df.drop_duplicates()

In [24]:
df['Invoice'].head(50)

0     489434
1     489434
2     489434
3     489434
4     489434
5     489434
6     489434
7     489434
8     489435
9     489435
10    489435
11    489435
12    489436
13    489436
14    489436
15    489436
16    489436
17    489436
18    489436
19    489436
20    489436
21    489436
22    489436
23    489436
24    489436
25    489436
26    489436
27    489436
28    489436
29    489436
30    489436
31    489437
32    489437
33    489437
34    489437
35    489437
36    489437
37    489437
38    489437
39    489437
40    489437
41    489437
42    489437
43    489437
44    489437
45    489437
46    489437
47    489437
48    489437
49    489437
Name: Invoice, dtype: object

In [28]:
df['InvoiceDate']

0         2009-12-01 07:45:00
1         2009-12-01 07:45:00
2         2009-12-01 07:45:00
3         2009-12-01 07:45:00
4         2009-12-01 07:45:00
                  ...
1067366   2011-12-09 12:50:00
1067367   2011-12-09 12:50:00
1067368   2011-12-09 12:50:00
1067369   2011-12-09 12:50:00
1067370   2011-12-09 12:50:00
Name: InvoiceDate, Length: 779425, dtype: datetime64[ns]

In [30]:
# creating new columns from date column

df['InvoiceYear'] = df['InvoiceDate'].dt.year
df['InvoiceMonth'] = df['InvoiceDate'].dt.month
df['InvoiceMonthName'] = df['InvoiceDate'].dt.month_name()
df['InvoiceDay'] = df['InvoiceDate'].dt.day
df['InvoiceDayName'] = df['InvoiceDate'].dt.day_name()

In [31]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,InvoiceYear,InvoiceMonth,InvoiceMonthName,InvoiceDay,InvoiceDayName
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,2009,12,December,1,Tuesday
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,2009,12,December,1,Tuesday
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,2009,12,December,1,Tuesday
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,2009,12,December,1,Tuesday
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,2009,12,December,1,Tuesday

In [32]:
# creating total_price

df['TotalPrice'] = df['Quantity'] * df['Price']

In [33]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,InvoiceYear,InvoiceMonth,InvoiceMonthName,InvoiceDay,InvoiceDayName,TotalPrice
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,2009,12,December,1,Tuesday,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,2009,12,December,1,Tuesday,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,2009,12,December,1,Tuesday,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,2009,12,December,1,Tuesday,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,2009,12,December,1,Tuesday,30.0

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 779425 entries, 0 to 1067370
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Invoice           779425 non-null  object
 1   StockCode         779425 non-null  object
 2   Description       779425 non-null  object
 3   Quantity          779425 non-null  int64
 4   InvoiceDate       779425 non-null  datetime64[ns]
 5   Price             779425 non-null  float64
 6   Customer ID       779425 non-null  object
 7   Country           779425 non-null  object
 8   InvoiceYear       779425 non-null  int32
 9   InvoiceMonth      779425 non-null  int32
 10  InvoiceMonthName  779425 non-null  object
 11  InvoiceDay        779425 non-null  int32
 12  InvoiceDayName    779425 non-null  object
 13  TotalPrice        779425 non-null  float64
dtypes: datetime64[ns](1), float64(2), int32(3), int64(1), object(7)
memory usage: 80.3+ MB

In [36]:
df["Country"].value_counts()

Country
United Kingdom          700388
Germany                  16432
EIRE                     15565
France                   13511
Netherlands               5085
Spain                     3662
Belgium                   3055
Switzerland               3005
Portugal                  2356
Australia                 1789
Channel Islands           1551
Italy                     1442
Sweden                    1317
Norway                    1289
Cyprus                    1136
Finland                   1032
Austria                    922
Denmark                    778
Greece                     657
Unspecified                518
Poland                     504
Japan                      468
USA                        409
United Arab Emirates       383
Singapore                  339
Israel                     319
Malta                      282
Canada                     228
Iceland                    222
Lithuania                  154
RSA                        122
Brazil                      94
Thailand                    76
European Community          60
Bahrain                     59
West Indies                 54
Korea                       53
Lebanon                     45
Nigeria                     30
Czech Republic              25
Saudi Arabia                 9
Name: count, dtype: int64

In [37]:
df["Country"].unique()

array(['United Kingdom', 'France', 'USA', 'Belgium', 'Australia', 'EIRE',
       'Germany', 'Portugal', 'Denmark', 'Netherlands', 'Poland',
       'Channel Islands', 'Spain', 'Cyprus', 'Greece', 'Norway',
       'Austria', 'Sweden', 'United Arab Emirates', 'Finland', 'Italy',
       'Switzerland', 'Japan', 'Unspecified', 'Nigeria', 'Malta', 'RSA',
       'Singapore', 'Bahrain', 'Thailand', 'Israel', 'Lithuania',
       'West Indies', 'Korea', 'Brazil', 'Canada', 'Iceland', 'Lebanon',
       'Saudi Arabia', 'Czech Republic', 'European Community'],
      dtype=object)

In [38]:
df.to_csv(r'C:\Users\HP\Downloads\Data Science\Final_Projects\retail-intelligence-analytics\data\cleaned.csv', index=False)